### PR TITLE
Fix schema errors

### PR DESCRIPTION
**Pull request by dgreisen**
@bbryantdccouncil: Gary successfully implemented the schema validator, found a bunch of errors. This PR fixes most of them. Please review and merge when you get a chance

### CODE REVIEW

**Comment by bbryantdccouncil** [comment]
David,

I have a couple of fixes to make to the code.  Can I push them to development?

Thanks.

Ben

**Comment by dgreisen** [comment]
@bbryantdccouncil: yes. go ahead.

**Comment by bbryantdccouncil** [comment]
David,

Why do you eliminate ".Statute text" in some files and not others?

**Comment by dgreisen** [comment]
I was trying to eliminate everywhere, as did not see those words in the
printed code. If they were there and I missed them sorry and happy to add
them back in.

**Comment by bbryantdccouncil** [comment]
It is ok to eliminate it everywhere, but I still see it in some of the files that you changed for other reasons.  You may want to search for that phrase “.Statute text” again in other files and remove it, otherwise it can be done at a later date.

**Pull request merged**
