### PR TITLE
Fix organic cites

### PR DESCRIPTION
**Pull request by dgreisen**

### CODE REVIEW

**Comment by bbryantdccouncil** [comment]
David,


I took a quick look at every change and they seem to make sense. I will double check them later this week when I have easier access to resources.  I am in an airport right now.


Thanks.


Ben

________________________________

**Comment by bbryantdccouncil** [comment]
Does this pull request eliminate section 6-1407.01?

**Comment by dgreisen** [comment]
Yes. 6-1407.01 and 6-1408.01 are identical. It appears that 6-1408.01 is the correct location for it (the organic section was § 8a).

**Comment by bbryantdccouncil** [comment]
David,

Actually, section 6-1407.01 is the correct location.  Section 8 of the organic is 6-1407. Section 9 of the organic is 6-1408.

Thanks.

Ben

**Comment by dgreisen** [comment]
@bbryantdccouncil: So does that mean that 6-1408.01 is wrong and should be removed?

**Comment by bbryantdccouncil** [comment]
Yes. 6-1408.01 should be removed.

**Comment by dgreisen** [comment]
@bbryantdccouncil: fixed.

**Comment by vqc** [comment]
Here is a link to a summary list of organic law citations that need additional attention: https://gist.github.com/dgreisen/c9c0518a263dc66cb158e26d64e15617#gistcomment-2021597.

**Comment by dgreisen** [comment]
@bbryantdccouncil: Here are 4 more than probably need manual fixes:
* 1-612.02a
* 38-151
* 5-563.01
* 5-561.02

**Comment by bbryantdccouncil** [comment]
OK.

**Pull request merged**
