### PR TITLE
technical: use law short titles from narrative history, when available

### PR DESCRIPTION
**Pull request by chrisrcoles**
…with proper title, parsed from narrative DCCODE-64. @dgreisen

### CODE REVIEW

**Comment by dgreisen** [comment]
This looks good. Could you please resubmit this PR split up into multiple commits so we can view the diffs on the web? It is relatively easy to split up by title. GitHub can display 1000 files, so splitting it into 4 or 5 commits should be safe. I usually split them up 1-9, 10-19, 20-29, etc so that, once you've added 1-9 individually to the first commit, you can just do `git add ./dc/council/code/titles/2*` etc for commits 2-5.

Also, for future reference, These commits are reviewed by Ben, the DC Codification Lawyer. So we want to make sure the commit messages make sense to him. So this commit I would call something like "technical: use short title from narrative, when exists"

**Comment by chrisrcoles** [comment]
Ok sure. No problem!

**Comment by chrisrcoles** [comment]
@dgreisen Let me know if this is okay!

**Comment by dgreisen** [comment]
perfect. Thanks

**Comment by dgreisen** [comment]
@bbryantdccouncil This is ready for review and merge. You will want to "squash and merge" from the drop-down menu after you have reviewed.

**Pull request merged**
